In [ ]:
from numpy import random

In [ ]:
#Generate any random number between 0 to 100
x = random.randint(100)

print(x)

#Generate any five numbers between 0 to 100
x=random.randint(100, size=(5))

print(x)

#Generate a 2 dimensional array with 3 rows, each row containing 3 random integers from 0 to 100:
x = random.randint(100, size=(3, 3))

print(x)


#Generate random number from array
x = random.choice([1, 4, 7, 8])

print(x)


73
[91 71 73 61 35]
[[15 26 73]
 [15 72 62]
 [92 73  8]]
4
